import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "FreeJobAlert Pilot Review | JobOye",
  description: "Review the three selected FreeJobAlert source inventory records and post breakdown.",
  robots: { index: false, follow: false, noarchive: true },
};

const items = [
  { id: "3071727", title: "UCSL Supervisor Recruitment 2026", org: "Udupi Cochin Shipyard Limited", url: "https://www.freejobalert.com/articles/ucsl-supervisor-recruitment-2026-apply-online-3071727", deadline: "28 Oct 2026", vacancies: 2, location: "Malpe, Karnataka", summary: "Reported S1 scale ₹28,000–₹110,000; upper age 45 as of closing date. Selection reportedly includes objective test, descriptive test and experience presentation.", posts: [{name:"Supervisor (Nesting)",n:1,pay:"S1 grade; reported emoluments ₹56,896/month",qual:"Three-year relevant engineering diploma and relevant experience reported; verify official notice."},{name:"Supervisor (Mechanical)",n:1,pay:"S1 grade; reported emoluments ₹56,896/month",qual:"Three-year Mechanical/Marine diploma and relevant experience reported; verify official notice."}] },
  { id: "3071555", title: "MDU Recruitment 2026 — 7 Project Posts", org: "Maharshi Dayanand University, Rohtak", url: "https://www.freejobalert.com/articles/mdu-recruitment-2026-apply-online-for-7-field-investigator-research-assistant-and-more-posts-3071555", deadline: "17 Oct 2026", vacancies: 7, location: "Gurugram, Haryana", summary: "Reported Haryana State Research Fund project roles. Email application; 19 Oct 2026 interview date is described as tentative.", posts: [{name:"Research Assistant",n:1,pay:"₹37,000/month; up to 4 months",qual:"Relevant postgraduate qualification; PhD/NET also mentioned in indexed summary. Verify."},{name:"Project Fellow",n:1,pay:"₹25,000/month; up to 6 months",qual:"Relevant postgraduate qualification reported; verify."},{name:"Field Investigator",n:5,pay:"₹15,000/month; up to 5 months",qual:"Graduate/postgraduate eligibility reported; verify."}] },
  { id: "3071441", title: "AAI Consultant Recruitment 2026", org: "Airports Authority of India / EdCIL (as reported)", url: "https://www.freejobalert.com/articles/aai-consultant-recruitment-2026-apply-online-3071441", deadline: "25 Oct 2026", vacancies: 3, location: "Mumbai, Maharashtra", summary: "Reported consultant engagement at ₹120,000/month all-inclusive; upper age 40 as of closing date; initial tenure one year with extension provision.", posts: [{name:"Consultant (Content Writer)",n:1,pay:"₹120,000/month",qual:"Relevant degree combination and 5–8 years' content/editorial experience reported; verify."},{name:"Consultant (Graphic Designer)",n:1,pay:"₹120,000/month",qual:"Relevant design qualification and 5–8 years' experience reported; verify."},{name:"Consultant (Video Editor)",n:1,pay:"₹120,000/month",qual:"Relevant media qualification and 5–8 years' editing experience reported; verify."}] }
];

export default function FjaReviewPage() {
  const postCount = items.reduce((n, r) => n + r.posts.length, 0);
  return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
    <div className="mb-6 flex items-center justify-between gap-3"><Link href="/" className="text-sm font-medium text-blue-700 hover:underline">← JobOye home</Link><span className="rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-900">Review only · noindex</span></div>
    <header className="mb-8"><p className="text-sm font-semibold uppercase tracking-wide text-slate-500">Source inventory pilot · 10 October 2026</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">FreeJobAlert: 3 recruitment records</h1><p className="mt-3 max-w-3xl text-slate-600">Review the three selected source articles and their post-level breakdown. This is competitor-source research, not official verification or public JobOye vacancy publication.</p>
      <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Recruitments" value={String(items.length)}/><Metric label="Post candidates" value={String(postCount)}/><Metric label="Reported vacancies" value={String(items.reduce((n,r)=>n+r.vacancies,0))}/><Metric label="Officially verified" value="0 / 3"/></div>
    </header>
    <div className="mb-8 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Data quality notice:</strong> this review view uses indexed article summaries to make the pilot inspectable. Original HTML has not yet been captured for these rows and official notification URLs are not confirmed. Treat all post-wise qualifications and details as provisional. Records remain outside canonical JobOye recruitment/post tables and the sitemap.</div>
    <div className="space-y-6">{items.map(r=><section key={r.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-200 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">FJA article ID {r.id}</p><h2 className="mt-1 text-xl font-bold text-slate-950">{r.title}</h2><p className="mt-1 text-sm text-slate-600">{r.org}</p></div><a href={r.url} target="_blank" rel="noreferrer" className="text-sm font-semibold text-blue-700 hover:underline">Open source article ↗</a></div>
      <div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><Fact label="Reported vacancies" value={String(r.vacancies)}/><Fact label="Reported deadline" value={r.deadline}/><Fact label="Location" value={r.location}/></div><p className="mt-4 text-sm leading-6 text-slate-700">{r.summary}</p></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Post candidate</th><th className="px-5 py-3">Vacancies</th><th className="px-5 py-3">Reported pay / tenure</th><th className="px-5 py-3">Qualification / evidence note</th></tr></thead><tbody>{r.posts.map(p=><tr key={p.name} className="border-t border-slate-100 align-top"><td className="px-5 py-4 font-semibold text-slate-900">{p.name}</td><td className="px-5 py-4 tabular-nums">{p.n}</td><td className="px-5 py-4 text-slate-700">{p.pay}</td><td className="px-5 py-4 leading-6 text-slate-600">{p.qual}</td></tr>)}</tbody></table></div>
      <div className="border-t border-slate-100 px-5 py-3 text-xs text-slate-500">Verification pending · HTML capture pending · Canonical JobOye publication blocked</div>
    </section>)}</div>
    <footer className="mt-8 border-t border-slate-200 pt-5 text-sm text-slate-500">Review-only page. Confirm details against the official notification before acting on any vacancy.</footer>
  </main>;
}
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-xl border border-slate-200 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums text-slate-950">{value}</p></div>; }
function Fact({label,value}:{label:string;value:string}) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold text-slate-900">{value}</p></div>; }
