import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";

// Versioned migration runner. Replaces `drizzle-kit push`, which crashes on
// this Supabase database (drizzle-kit 0.31.11 CHECK-constraint parser bug).
//
// Uses Drizzle's official migrator: it creates a `drizzle.__drizzle_migrations`
// tracking table, applies only migrations not yet recorded there, and is safe
// to re-run (idempotent). Migrations live in ./drizzle (SQL generated by
// `npm run db:generate`).
//
// NOTE on this project's REMOTE db: the initial schema was applied out-of-band
// (via the Supabase API) before this runner existed, so the tracking table has
// no record of 0000_init. Running this against that already-synced database
// would try to re-create existing tables and fail. It is safe to run against a
// FRESH database (new Supabase project / preview branch). To adopt versioned
// migrations on the existing remote db, baseline it first (record 0000_init as
// applied) — ask before doing that.
async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("DATABASE_URL is not set. Aborting.");
    process.exit(1);
  }

  const migrationsFolder = path.resolve(process.cwd(), "drizzle");
  const files = readdirSync(migrationsFolder)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  if (files.length === 0) {
    console.log("No migration files found in ./drizzle — nothing to do.");
    process.exit(0);
  }

  console.log(`Found ${files.length} migration file(s):`);
  for (const f of files) {
    const lines = readFileSync(path.join(migrationsFolder, f), "utf8").split(
      "\n",
    ).length;
    console.log(`  • ${f} (${lines} lines)`);
  }

  // Dedicated single connection for migrations (no pooling reuse).
  const sql = postgres(url, { max: 1, prepare: false });
  const db = drizzle(sql);

  console.log("Applying pending migrations…");
  await migrate(db, { migrationsFolder });
  console.log("Migrations up to date.");

  await sql.end();
  process.exit(0);
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
