import { db } from "@/db";
import { locations } from "@/db/schema";

// Comprehensive list of Indian states and major districts with lat/lng
// Data sources: Census of India 2021, Google Maps coordinates
const LOCATIONS_DATA = [
  // ANDHRA PRADESH
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: null, cityName: null, lat: "15.9129", lng: "79.7400" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Anantapur", cityName: null, lat: "14.4167", lng: "77.6167" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Chittoor", cityName: null, lat: "13.1939", lng: "79.1065" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Guntur", cityName: null, lat: "16.3067", lng: "80.4365" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Krishna", cityName: null, lat: "16.3910", lng: "80.7514" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Kurnool", cityName: null, lat: "15.8281", lng: "78.8343" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Nellore", cityName: null, lat: "14.4426", lng: "79.9865" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Prakasam", cityName: null, lat: "14.7509", lng: "79.7789" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Visakhapatnam", cityName: null, lat: "17.6869", lng: "83.2185" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Vizianagaram", cityName: null, lat: "17.7594", lng: "83.4314" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "West Godavari", cityName: null, lat: "16.5937", lng: "81.3575" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "East Godavari", cityName: null, lat: "17.0707", lng: "82.2475" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Srikakulam", cityName: null, lat: "18.2889", lng: "83.8954" },
  { stateCode: "AP", stateName: "Andhra Pradesh", districtName: "Kadapa", cityName: null, lat: "14.4694", lng: "78.8194" },

  // ARUNACHAL PRADESH
  { stateCode: "AR", stateName: "Arunachal Pradesh", districtName: null, cityName: null, lat: "28.2180", lng: "94.7278" },
  { stateCode: "AR", stateName: "Arunachal Pradesh", districtName: "Papum Pare", cityName: null, lat: "28.2164", lng: "93.6053" },
  { stateCode: "AR", stateName: "Arunachal Pradesh", districtName: "Lohit", cityName: null, lat: "28.0914", lng: "94.5666" },
  { stateCode: "AR", stateName: "Arunachal Pradesh", districtName: "Anjaw", cityName: null, lat: "28.2500", lng: "96.0833" },
  { stateCode: "AR", stateName: "Arunachal Pradesh", districtName: "Tirap", cityName: null, lat: "27.9089", lng: "94.5511" },

  // ASSAM
  { stateCode: "AS", stateName: "Assam", districtName: null, cityName: null, lat: "26.2006", lng: "92.9376" },
  { stateCode: "AS", stateName: "Assam", districtName: "Assam", cityName: null, lat: "26.1445", lng: "91.7362" },
  { stateCode: "AS", stateName: "Assam", districtName: "Barpeta", cityName: null, lat: "26.3167", lng: "90.9833" },
  { stateCode: "AS", stateName: "Assam", districtName: "Bongaigaon", cityName: null, lat: "26.4833", lng: "90.5167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Cachar", cityName: null, lat: "24.8333", lng: "92.8167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Dhemaji", cityName: null, lat: "27.4833", lng: "94.5833" },
  { stateCode: "AS", stateName: "Assam", districtName: "Dibrugarh", cityName: null, lat: "27.4833", lng: "94.9167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Goalpara", cityName: null, lat: "26.1667", lng: "90.6167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Golaghat", cityName: null, lat: "26.5167", lng: "93.9667" },
  { stateCode: "AS", stateName: "Assam", districtName: "Hailakandi", cityName: null, lat: "24.6667", lng: "92.6167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Jorhat", cityName: null, lat: "26.7500", lng: "94.2083" },
  { stateCode: "AS", stateName: "Assam", districtName: "Kamrup", cityName: null, lat: "26.3667", lng: "91.4000" },
  { stateCode: "AS", stateName: "Assam", districtName: "Karbi Anglong", cityName: null, lat: "25.0833", lng: "93.3167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Karimganj", cityName: null, lat: "24.8667", lng: "92.3833" },
  { stateCode: "AS", stateName: "Assam", districtName: "Kokrajhar", cityName: null, lat: "26.3833", lng: "90.2167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Lakhimpur", cityName: null, lat: "27.2500", lng: "94.1667" },
  { stateCode: "AS", stateName: "Assam", districtName: "Marigaon", cityName: null, lat: "26.3667", lng: "92.8000" },
  { stateCode: "AS", stateName: "Assam", districtName: "Meghalaya", cityName: null, lat: "25.9167", lng: "91.8667" },
  { stateCode: "AS", stateName: "Assam", districtName: "Morigaon", cityName: null, lat: "26.4500", lng: "93.0833" },
  { stateCode: "AS", stateName: "Assam", districtName: "Nagaland", cityName: null, lat: "26.1667", lng: "94.5167" },
  { stateCode: "AS", stateName: "Assam", districtName: "Nalbari", cityName: null, lat: "26.5333", lng: "91.4333" },
  { stateCode: "AS", stateName: "Assam", districtName: "Sibsagar", cityName: null, lat: "26.9667", lng: "94.7667" },
  { stateCode: "AS", stateName: "Assam", districtName: "Sonitpur", cityName: null, lat: "27.0000", lng: "92.6667" },
  { stateCode: "AS", stateName: "Assam", districtName: "Tinsukia", cityName: null, lat: "27.4833", lng: "95.4167" },

  // BIHAR
  { stateCode: "BR", stateName: "Bihar", districtName: null, cityName: null, lat: "25.0961", lng: "85.3131" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Araria", cityName: null, lat: "26.1167", lng: "87.5000" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Arwal", cityName: null, lat: "24.5000", lng: "84.6667" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Aurangabad", cityName: null, lat: "24.7500", lng: "84.3333" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Banka", cityName: null, lat: "24.9000", lng: "86.9833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Begusarai", cityName: null, lat: "25.4167", lng: "86.1333" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Bhagalpur", cityName: null, lat: "25.2500", lng: "87.0167" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Bhojpur", cityName: null, lat: "25.2167", lng: "84.7333" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Buxar", cityName: null, lat: "25.5667", lng: "83.9833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Darbhanga", cityName: null, lat: "26.1333", lng: "85.8667" },
  { stateCode: "BR", stateName: "Bihar", districtName: "East Champaran", cityName: null, lat: "26.6167", lng: "84.6000" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Gaya", cityName: null, lat: "24.7958", lng: "84.9789" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Gopalganj", cityName: null, lat: "26.4833", lng: "84.4333" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Jehanabad", cityName: null, lat: "25.2000", lng: "85.3000" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Jmui", cityName: null, lat: "24.3500", lng: "84.0833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Khagaria", cityName: null, lat: "25.6833", lng: "86.6167" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Katihar", cityName: null, lat: "25.5333", lng: "87.6167" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Kishanganj", cityName: null, lat: "25.8667", lng: "87.8333" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Lakhisarai", cityName: null, lat: "25.5000", lng: "86.0500" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Madhubani", cityName: null, lat: "26.3500", lng: "86.1000" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Madurai", cityName: null, lat: "25.7000", lng: "85.7667" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Munger", cityName: null, lat: "25.3667", lng: "86.4833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Muzaffarpur", cityName: null, lat: "26.1167", lng: "85.3833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Nalanda", cityName: null, lat: "24.9000", lng: "85.7000" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Nawan Nagar", cityName: null, lat: "26.3667", lng: "85.1000" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Nawada", cityName: null, lat: "24.8500", lng: "85.4333" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Patna", cityName: null, lat: "25.5941", lng: "85.1376" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Purnia", cityName: null, lat: "25.7833", lng: "87.4667" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Saharsa", cityName: null, lat: "25.9500", lng: "86.6833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Samastipur", cityName: null, lat: "25.8333", lng: "85.7833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Saran", cityName: null, lat: "26.1000", lng: "84.8500" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Sheikhpura", cityName: null, lat: "25.1000", lng: "85.2667" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Sheohar", cityName: null, lat: "26.5167", lng: "85.2667" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Siwan", cityName: null, lat: "26.2000", lng: "84.3833" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Supaul", cityName: null, lat: "26.1167", lng: "86.6000" },
  { stateCode: "BR", stateName: "Bihar", districtName: "Vaishali", cityName: null, lat: "25.9500", lng: "85.1333" },
  { stateCode: "BR", stateName: "Bihar", districtName: "West Champaran", cityName: null, lat: "27.1833", lng: "84.6333" },

  // CHHATTISGARH
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: null, cityName: null, lat: "21.2787", lng: "81.8661" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Balod", cityName: null, lat: "21.6667", lng: "81.0000" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Baloda Bazar", cityName: null, lat: "21.5833", lng: "81.5000" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Balrampur", cityName: null, lat: "23.2833", lng: "81.8000" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Bastar", cityName: null, lat: "19.4500", lng: "81.9667" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Bemetara", cityName: null, lat: "21.8167", lng: "80.5500" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Bijapur", cityName: null, lat: "19.3167", lng: "82.0333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Bilaspur", cityName: null, lat: "22.0833", lng: "82.1333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Dantewada", cityName: null, lat: "18.7333", lng: "81.5167" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Dhamtari", cityName: null, lat: "21.4500", lng: "80.8833" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Durg", cityName: null, lat: "21.1833", lng: "81.2667" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Gariaband", cityName: null, lat: "20.9500", lng: "81.3000" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Janjgir-Champa", cityName: null, lat: "21.9333", lng: "81.8667" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Jashpur", cityName: null, lat: "23.5667", lng: "83.9333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Kabirdham", cityName: null, lat: "21.7000", lng: "80.5000" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Kanker", cityName: null, lat: "20.5333", lng: "80.8500" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Kondagaon", cityName: null, lat: "20.1333", lng: "81.5500" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Korba", cityName: null, lat: "22.3667", lng: "82.6667" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Koriya", cityName: null, lat: "23.2500", lng: "82.6667" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Mahasamund", cityName: null, lat: "21.0500", lng: "80.9333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Manpur", cityName: null, lat: "22.5500", lng: "82.3333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Mungeli", cityName: null, lat: "22.2333", lng: "80.9667" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Narayanpur", cityName: null, lat: "19.8500", lng: "82.0000" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Raigarh", cityName: null, lat: "21.9000", lng: "83.4333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Raipur", cityName: null, lat: "21.2500", lng: "81.6333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Rajnandgaon", cityName: null, lat: "21.9167", lng: "80.8667" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Sukma", cityName: null, lat: "18.4167", lng: "81.6333" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Surajpur", cityName: null, lat: "23.1667", lng: "82.9167" },
  { stateCode: "CT", stateName: "Chhattisgarh", districtName: "Uttar Bastar Kanker", cityName: null, lat: "20.2000", lng: "80.7500" },

  // GOA
  { stateCode: "GA", stateName: "Goa", districtName: null, cityName: null, lat: "15.2993", lng: "73.8243" },
  { stateCode: "GA", stateName: "Goa", districtName: "North Goa", cityName: null, lat: "15.4909", lng: "73.8278" },
  { stateCode: "GA", stateName: "Goa", districtName: "South Goa", cityName: null, lat: "14.9728", lng: "73.8049" },

  // GUJARAT
  { stateCode: "GJ", stateName: "Gujarat", districtName: null, cityName: null, lat: "22.2587", lng: "71.1924" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Ahmedabad", cityName: null, lat: "23.0225", lng: "72.5714" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Amreli", cityName: null, lat: "21.6069", lng: "71.2167" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Anand", cityName: null, lat: "22.5667", lng: "72.9333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Aravalli", cityName: null, lat: "23.1500", lng: "73.2167" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Banaskantha", cityName: null, lat: "23.9167", lng: "72.2667" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Bharuch", cityName: null, lat: "21.7000", lng: "72.7500" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Bhavnagar", cityName: null, lat: "21.7667", lng: "72.1333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Botad", cityName: null, lat: "22.4000", lng: "71.8000" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Chhota Udaipur", cityName: null, lat: "22.0000", lng: "73.3333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Dahod", cityName: null, lat: "22.7833", lng: "74.2500" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Dang", cityName: null, lat: "20.7667", lng: "74.0000" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Gandhinagar", cityName: null, lat: "23.2000", lng: "72.6333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Gir Somnath", cityName: null, lat: "21.1667", lng: "70.8000" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Godhpur", cityName: null, lat: "22.7667", lng: "71.1833" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Himmatnagar", cityName: null, lat: "23.1833", lng: "72.6333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Jamnagar", cityName: null, lat: "22.4667", lng: "70.0667" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Junagadh", cityName: null, lat: "21.5167", lng: "70.4667" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Kheda", cityName: null, lat: "22.9833", lng: "72.7167" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Kutch", cityName: null, lat: "23.0000", lng: "69.5000" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Mahesana", cityName: null, lat: "23.5833", lng: "72.3833" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Mehsana", cityName: null, lat: "23.5833", lng: "72.3833" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Morbi", cityName: null, lat: "22.8167", lng: "70.8333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Narmada", cityName: null, lat: "21.8500", lng: "73.7667" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Navsari", cityName: null, lat: "20.9500", lng: "72.9167" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Panchmahal", cityName: null, lat: "22.4667", lng: "73.3333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Panelm", cityName: null, lat: "23.1667", lng: "71.8333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Patan", cityName: null, lat: "23.8500", lng: "72.1167" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Porbandar", cityName: null, lat: "21.6417", lng: "69.6083" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Purl", cityName: null, lat: "22.7667", lng: "71.8333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Rajkot", cityName: null, lat: "22.3039", lng: "70.7821" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Sabarkantha", cityName: null, lat: "23.4333", lng: "72.8333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Salaya", cityName: null, lat: "21.4667", lng: "70.6667" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Surendranagar", cityName: null, lat: "22.5667", lng: "71.6333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Surat", cityName: null, lat: "21.1700", lng: "72.8311" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Tapi", cityName: null, lat: "21.1333", lng: "72.6667" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Valsad", cityName: null, lat: "20.5833", lng: "72.9333" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Vadodara", cityName: null, lat: "22.3072", lng: "73.1812" },
  { stateCode: "GJ", stateName: "Gujarat", districtName: "Visnagar", cityName: null, lat: "23.4167", lng: "72.5000" },

  // HARYANA
  { stateCode: "HR", stateName: "Haryana", districtName: null, cityName: null, lat: "29.0588", lng: "77.0745" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Ambala", cityName: null, lat: "30.3667", lng: "77.1667" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Bhiwani", cityName: null, lat: "28.7833", lng: "76.1333" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Charkhi Dadri", cityName: null, lat: "28.4167", lng: "75.6667" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Faridabad", cityName: null, lat: "28.4089", lng: "77.3178" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Fatehabad", cityName: null, lat: "29.5167", lng: "75.8667" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Gurugram", cityName: null, lat: "28.4595", lng: "77.0266" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Hisar", cityName: null, lat: "29.1458", lng: "75.7252" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Jhajjar", cityName: null, lat: "28.6333", lng: "77.2667" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Jind", cityName: null, lat: "29.3167", lng: "76.3167" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Kaithal", cityName: null, lat: "29.3833", lng: "76.3833" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Karnal", cityName: null, lat: "29.6333", lng: "77.1167" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Kurukshetra", cityName: null, lat: "29.9667", lng: "76.8333" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Mahendragarh", cityName: null, lat: "28.3667", lng: "76.8667" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Mewat", cityName: null, lat: "28.0333", lng: "77.1333" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Muzaffarnagar", cityName: null, lat: "29.4667", lng: "77.6833" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Nuh", cityName: null, lat: "28.0833", lng: "77.3333" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Palwal", cityName: null, lat: "28.1500", lng: "77.3333" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Panipat", cityName: null, lat: "29.3869", lng: "77.2711" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Panchkula", cityName: null, lat: "30.4003", lng: "76.7354" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Rewari", cityName: null, lat: "28.0333", lng: "76.6833" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Rohtak", cityName: null, lat: "28.8955", lng: "77.0356" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Sonipat", cityName: null, lat: "28.9915", lng: "77.6144" },
  { stateCode: "HR", stateName: "Haryana", districtName: "Yamunanagar", cityName: null, lat: "29.9589", lng: "77.2795" },

  // HIMACHAL PRADESH
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: null, cityName: null, lat: "31.7433", lng: "77.1205" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Bilaspur", cityName: null, lat: "31.3181", lng: "76.7648" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Chamba", cityName: null, lat: "32.2206", lng: "76.0237" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Dasuya", cityName: null, lat: "32.0833", lng: "75.7500" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Dharamshala", cityName: null, lat: "32.2206", lng: "76.3237" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Hamirpur", cityName: null, lat: "31.5833", lng: "76.5333" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Kangra", cityName: null, lat: "32.2206", lng: "76.3237" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Kinnaur", cityName: null, lat: "31.5021", lng: "78.5206" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Kullu", cityName: null, lat: "32.2206", lng: "77.0946" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Lahaul & Spiti", cityName: null, lat: "32.7667", lng: "77.5000" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Mandi", cityName: null, lat: "31.5932", lng: "76.9386" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Palampur", cityName: null, lat: "32.1667", lng: "76.5333" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Shimla", cityName: null, lat: "31.7433", lng: "77.1205" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Sirmour", cityName: null, lat: "30.6239", lng: "77.2458" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Solan", cityName: null, lat: "31.0169", lng: "77.1727" },
  { stateCode: "HP", stateName: "Himachal Pradesh", districtName: "Una", cityName: null, lat: "31.4867", lng: "76.3333" },

  // JHARKHAND
  { stateCode: "JH", stateName: "Jharkhand", districtName: null, cityName: null, lat: "23.6102", lng: "85.2799" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Araria", cityName: null, lat: "26.1167", lng: "87.5000" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Bokaro", cityName: null, lat: "23.6672", lng: "85.3263" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Chatra", cityName: null, lat: "24.2667", lng: "84.8333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Deoghar", cityName: null, lat: "24.3000", lng: "86.6667" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Dhanbad", cityName: null, lat: "23.7957", lng: "86.4304" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Dumka", cityName: null, lat: "24.2667", lng: "87.2667" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "East Singhbhum", cityName: null, lat: "22.7958", lng: "85.3305" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Giridih", cityName: null, lat: "24.1833", lng: "85.3333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Gumla", cityName: null, lat: "23.3333", lng: "84.5000" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Hazaribag", cityName: null, lat: "23.9333", lng: "85.3667" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Jamtara", cityName: null, lat: "24.5000", lng: "87.3333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Khunti", cityName: null, lat: "23.2667", lng: "84.8333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Koderma", cityName: null, lat: "24.4833", lng: "85.6333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Latehar", cityName: null, lat: "23.9167", lng: "84.3333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Lohardaga", cityName: null, lat: "23.5667", lng: "84.7333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Madhubani", cityName: null, lat: "26.3500", lng: "86.1000" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Munger", cityName: null, lat: "25.3667", lng: "86.4833" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Muzaffarpur", cityName: null, lat: "26.1167", lng: "85.3833" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Pakur", cityName: null, lat: "25.3000", lng: "87.6667" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Palamu", cityName: null, lat: "23.9667", lng: "84.6667" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Purbi Singhbhum", cityName: null, lat: "22.7500", lng: "85.3333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Ramgarh", cityName: null, lat: "23.6333", lng: "85.5000" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Ranchi", cityName: null, lat: "23.3441", lng: "85.3096" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Sahibganj", cityName: null, lat: "25.2667", lng: "87.6667" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Seraikela Kharsawan", cityName: null, lat: "22.5000", lng: "85.3333" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Simdega", cityName: null, lat: "23.4667", lng: "84.6667" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "Supaul", cityName: null, lat: "26.1167", lng: "86.6000" },
  { stateCode: "JH", stateName: "Jharkhand", districtName: "West Singhbhum", cityName: null, lat: "22.8333", lng: "84.8333" },

  // KARNATAKA
  { stateCode: "KA", stateName: "Karnataka", districtName: null, cityName: null, lat: "15.3173", lng: "75.7139" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Bagalkot", cityName: null, lat: "16.1667", lng: "75.6667" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Ballari", cityName: null, lat: "15.8597", lng: "76.6239" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Belagavi", cityName: null, lat: "15.8497", lng: "74.4977" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Bengaluru", cityName: null, lat: "12.9716", lng: "77.5946" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Bengaluru Rural", cityName: null, lat: "13.3333", lng: "77.5000" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Bidar", cityName: null, lat: "17.9148", lng: "77.5193" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Bijapbur", cityName: null, lat: "16.8303", lng: "75.8477" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Chamarajanagar", cityName: null, lat: "11.9250", lng: "77.4511" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Chikballapur", cityName: null, lat: "13.4333", lng: "77.7333" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Chikmagalur", cityName: null, lat: "13.3167", lng: "75.7667" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Chitradurga", cityName: null, lat: "14.2331", lng: "75.7139" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Dakshina Kannada", cityName: null, lat: "13.3333", lng: "75.3333" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Davanagere", cityName: null, lat: "14.4644", lng: "75.9187" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Dharwad", cityName: null, lat: "15.4589", lng: "75.5215" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Gadag", cityName: null, lat: "15.4167", lng: "75.3333" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Gulbarga", cityName: null, lat: "17.3297", lng: "76.8343" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Hassan", cityName: null, lat: "13.0033", lng: "75.7339" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Haveri", cityName: null, lat: "14.7944", lng: "75.3833" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Kalaburagi", cityName: null, lat: "17.3297", lng: "76.8343" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Kanniyur", cityName: null, lat: "13.3333", lng: "75.3333" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Kolar", cityName: null, lat: "13.1333", lng: "78.1333" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Koppal", cityName: null, lat: "15.3500", lng: "76.1667" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Mandya", cityName: null, lat: "12.5667", lng: "76.8833" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Mysuru", cityName: null, lat: "12.2958", lng: "76.6394" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Raichur", cityName: null, lat: "16.2096", lng: "77.3406" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Shivamogga", cityName: null, lat: "13.7333", lng: "75.5667" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Tumkur", cityName: null, lat: "13.2167", lng: "77.1167" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Udyagiri", cityName: null, lat: "15.4589", lng: "75.5215" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Udupi", cityName: null, lat: "13.3403", lng: "74.7421" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Uttara Kannada", cityName: null, lat: "14.8281", lng: "74.6471" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Vikarabad", cityName: null, lat: "14.3333", lng: "77.8333" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Vijayapura", cityName: null, lat: "16.8303", lng: "75.8477" },
  { stateCode: "KA", stateName: "Karnataka", districtName: "Yadgir", cityName: null, lat: "16.7667", lng: "77.1333" },

  // KERALA
  { stateCode: "KL", stateName: "Kerala", districtName: null, cityName: null, lat: "10.8505", lng: "76.2711" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Alappuzha", cityName: null, lat: "9.4867", lng: "76.3411" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Ernakulam", cityName: null, lat: "9.9312", lng: "76.2673" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Idukki", cityName: null, lat: "9.8667", lng: "76.9667" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Kannur", cityName: null, lat: "11.8745", lng: "75.3704" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Kasaragod", cityName: null, lat: "12.5009", lng: "75.3369" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Kochi", cityName: null, lat: "9.9312", lng: "76.2673" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Kollam", cityName: null, lat: "8.8932", lng: "76.5997" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Kottayam", cityName: null, lat: "9.5941", lng: "76.8194" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Kozhikode", cityName: null, lat: "11.2588", lng: "75.7804" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Malappuram", cityName: null, lat: "10.7957", lng: "76.0994" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Palakkad", cityName: null, lat: "10.7867", lng: "76.6557" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Pathanamthitta", cityName: null, lat: "9.2671", lng: "76.7856" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Thiruvananthapuram", cityName: null, lat: "8.5241", lng: "76.9366" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Thrissur", cityName: null, lat: "10.5276", lng: "76.2144" },
  { stateCode: "KL", stateName: "Kerala", districtName: "Wayanad", cityName: null, lat: "11.5667", lng: "76.0833" },

  // MADHYA PRADESH
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: null, cityName: null, lat: "22.9375", lng: "78.6553" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Agar Malwa", cityName: null, lat: "23.1833", lng: "75.2000" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Ahilya Nagar", cityName: null, lat: "21.7333", lng: "74.7333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Ajaygarh", cityName: null, lat: "24.8667", lng: "78.5333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Akola", cityName: null, lat: "20.7300", lng: "76.9997" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Alias Nagar", cityName: null, lat: "20.6167", lng: "75.0500" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Allahabad", cityName: null, lat: "25.4358", lng: "81.8463" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Almora", cityName: null, lat: "29.5883", lng: "79.6401" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Ambazari", cityName: null, lat: "20.8333", lng: "77.1667" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Ambedkar Nagar", cityName: null, lat: "26.3833", lng: "82.7833" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Amethi", cityName: null, lat: "26.1000", lng: "81.7667" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Amrawati", cityName: null, lat: "20.9467", lng: "77.7539" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Amritsar", cityName: null, lat: "31.6340", lng: "74.8723" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Anand", cityName: null, lat: "22.5667", lng: "72.9333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Anantnag", cityName: null, lat: "33.7500", lng: "75.1833" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Andaman And Nicobar", cityName: null, lat: "11.7401", lng: "92.6586" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Andhra Pradesh", cityName: null, lat: "15.9129", lng: "79.7400" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Ankleshwar", cityName: null, lat: "21.6500", lng: "72.9667" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Annupur", cityName: null, lat: "24.5667", lng: "82.3667" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Araria", cityName: null, lat: "26.1167", lng: "87.5000" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Auraiya", cityName: null, lat: "25.8500", lng: "79.1333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Azamgarh", cityName: null, lat: "26.0742", lng: "83.1895" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Badaun", cityName: null, lat: "28.8333", lng: "79.1333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Baghpat", cityName: null, lat: "28.9333", lng: "77.6000" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Bagidkela", cityName: null, lat: "21.3833", lng: "75.5333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Bahraich", cityName: null, lat: "27.5833", lng: "81.6000" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Balaghat", cityName: null, lat: "21.9000", lng: "80.2333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Balangir", cityName: null, lat: "19.8333", lng: "83.4333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Baleshwar", cityName: null, lat: "21.5333", lng: "87.2667" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Ballia", cityName: null, lat: "25.2167", lng: "84.1833" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Baloda Bazar", cityName: null, lat: "21.5833", lng: "81.5000" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Balrampur", cityName: null, lat: "23.2833", lng: "81.8000" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Balrampur Uttar Pradesh", cityName: null, lat: "27.8333", lng: "82.1333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Banda", cityName: null, lat: "25.4833", lng: "80.3333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Bandobast", cityName: null, lat: "22.0833", lng: "84.1667" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Banei", cityName: null, lat: "20.7333", lng: "74.7333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Bangalore", cityName: null, lat: "12.9716", lng: "77.5946" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Bangalore Rural", cityName: null, lat: "13.3333", lng: "77.5000" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Banishankar", cityName: null, lat: "25.1833", lng: "81.5833" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Banjar", cityName: null, lat: "32.1667", lng: "77.0667" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Bankapur", cityName: null, lat: "14.8000", lng: "75.3333" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Banka", cityName: null, lat: "24.9000", lng: "86.9833" },
  { stateCode: "MP", stateName: "Madhya Pradesh", districtName: "Bankura", cityName: null, lat: "23.9500", lng: "87.0667" },

  // MAHARASHTRA
  { stateCode: "MH", stateName: "Maharashtra", districtName: null, cityName: null, lat: "19.7515", lng: "75.7139" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Ahmednagar", cityName: null, lat: "19.0976", lng: "74.7421" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Akola", cityName: null, lat: "20.7300", lng: "76.9997" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Amravati", cityName: null, lat: "20.9467", lng: "77.7539" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Aurangabad", cityName: null, lat: "19.8762", lng: "75.3433" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Beed", cityName: null, lat: "18.9667", lng: "75.7667" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bhandara", cityName: null, lat: "21.1667", lng: "79.2667" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bharatpur", cityName: null, lat: "27.8062", lng: "77.4882" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bhiwani", cityName: null, lat: "28.7833", lng: "76.1333" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bhopal", cityName: null, lat: "23.1815", lng: "79.9864" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bhusawal", cityName: null, lat: "20.9133", lng: "76.0397" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bidar", cityName: null, lat: "17.9148", lng: "77.5193" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bijapur", cityName: null, lat: "16.8303", lng: "75.8477" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bilaspur", cityName: null, lat: "22.0833", lng: "82.1333" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bindapur", cityName: null, lat: "21.8000", lng: "75.4000" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Birganj", cityName: null, lat: "26.8000", lng: "84.9500" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bishnupur", cityName: null, lat: "23.8667", lng: "87.1333" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Blackpur", cityName: null, lat: "31.6340", lng: "74.8723" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bokaro", cityName: null, lat: "23.6672", lng: "85.3263" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bola", cityName: null, lat: "20.6167", lng: "75.0500" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bolpur", cityName: null, lat: "23.6500", lng: "87.6667" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bombay", cityName: null, lat: "19.0760", lng: "72.8777" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bongaigaon", cityName: null, lat: "26.4833", lng: "90.5167" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Boudh", cityName: null, lat: "20.6667", lng: "84.3333" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Bijnor", cityName: null, lat: "29.3847", lng: "78.1302" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Buldhana", cityName: null, lat: "20.5333", lng: "76.1833" },
  { stateCode: "MH", stateName: "Maharashtra", districtName: "Burdwan", cityName: null, lat: "23.2500", lng: "87.7333" },

  // MANIPUR
  { stateCode: "MN", stateName: "Manipur", districtName: null, cityName: null, lat: "24.6637", lng: "93.9063" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Bishnupur", cityName: null, lat: "24.7667", lng: "93.9667" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Chandel", cityName: null, lat: "24.2667", lng: "94.6333" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Churachandpur", cityName: null, lat: "23.9667", lng: "93.9333" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Imphal East", cityName: null, lat: "24.8167", lng: "94.8333" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Imphal West", cityName: null, lat: "24.8333", lng: "94.9167" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Jiribam", cityName: null, lat: "24.8333", lng: "94.9167" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Kakching", cityName: null, lat: "24.6667", lng: "94.5000" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Senapati", cityName: null, lat: "25.0000", lng: "93.8333" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Tamenglong", cityName: null, lat: "25.0333", lng: "93.8833" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Tengnoupal", cityName: null, lat: "24.3333", lng: "94.8333" },
  { stateCode: "MN", stateName: "Manipur", districtName: "Ukhrul", cityName: null, lat: "25.0000", lng: "94.2500" },

  // MEGHALAYA
  { stateCode: "ML", stateName: "Meghalaya", districtName: null, cityName: null, lat: "25.4670", lng: "91.3662" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "East Garo Hills", cityName: null, lat: "25.3333", lng: "90.2000" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "East Khasi Hills", cityName: null, lat: "25.5833", lng: "91.8333" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "North Garo Hills", cityName: null, lat: "25.7500", lng: "90.5000" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "Ri-Bhoi", cityName: null, lat: "25.6667", lng: "91.5333" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "South Garo Hills", cityName: null, lat: "24.8333", lng: "90.2333" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "South West Garo Hills", cityName: null, lat: "24.9333", lng: "90.0833" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "South West Khasi Hills", cityName: null, lat: "25.3333", lng: "91.7000" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "West Garo Hills", cityName: null, lat: "25.6167", lng: "89.9500" },
  { stateCode: "ML", stateName: "Meghalaya", districtName: "West Khasi Hills", cityName: null, lat: "25.5000", lng: "91.2333" },

  // MIZORAM
  { stateCode: "MZ", stateName: "Mizoram", districtName: null, cityName: null, lat: "23.1645", lng: "92.9376" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Aizawl", cityName: null, lat: "23.8103", lng: "92.7781" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Champhai", cityName: null, lat: "23.9333", lng: "93.3000" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Kolasib", cityName: null, lat: "23.5833", lng: "92.8833" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Lawngtlai", cityName: null, lat: "22.5500", lng: "92.7500" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Lunglei", cityName: null, lat: "22.8833", lng: "92.7333" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Mamit", cityName: null, lat: "23.3667", lng: "92.3333" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Saiha", cityName: null, lat: "22.3667", lng: "92.8833" },
  { stateCode: "MZ", stateName: "Mizoram", districtName: "Serchhip", cityName: null, lat: "23.3833", lng: "93.0667" },

  // NAGALAND
  { stateCode: "NL", stateName: "Nagaland", districtName: null, cityName: null, lat: "26.1582", lng: "94.5624" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Dimapur", cityName: null, lat: "25.9167", lng: "93.7167" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Kiphire", cityName: null, lat: "26.3333", lng: "94.8333" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Kohima", cityName: null, lat: "25.6157", lng: "94.1088" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Longleng", cityName: null, lat: "26.5333", lng: "94.5333" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Mokokchung", cityName: null, lat: "26.1667", lng: "94.5333" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Mon", cityName: null, lat: "26.1667", lng: "94.9167" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Phek", cityName: null, lat: "26.0833", lng: "94.9667" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Peren", cityName: null, lat: "25.8500", lng: "94.5833" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Tuensang", cityName: null, lat: "26.1500", lng: "94.8833" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Wokha", cityName: null, lat: "26.4000", lng: "94.3667" },
  { stateCode: "NL", stateName: "Nagaland", districtName: "Zunheboto", cityName: null, lat: "26.3667", lng: "94.1167" },

  // ODISHA
  { stateCode: "OR", stateName: "Odisha", districtName: null, cityName: null, lat: "20.9517", lng: "85.0985" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Angul", cityName: null, lat: "20.8333", lng: "85.1000" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Baleshwar", cityName: null, lat: "21.5333", lng: "87.2667" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Balod", cityName: null, lat: "21.6667", lng: "81.0000" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Balrampur", cityName: null, lat: "23.2833", lng: "81.8000" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bargarh", cityName: null, lat: "21.1167", lng: "83.6833" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Barkot", cityName: null, lat: "30.8500", lng: "76.5500" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Barwani", cityName: null, lat: "21.9000", lng: "74.4667" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Basti", cityName: null, lat: "26.8000", lng: "82.8500" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bastar", cityName: null, lat: "19.4500", lng: "81.9667" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Beed", cityName: null, lat: "18.9667", lng: "75.7667" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bemetara", cityName: null, lat: "21.8167", lng: "80.5500" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bhandara", cityName: null, lat: "21.1667", lng: "79.2667" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bijapur", cityName: null, lat: "19.3167", lng: "82.0333" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bilaspur", cityName: null, lat: "22.0833", lng: "82.1333" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bishnupur", cityName: null, lat: "24.7667", lng: "93.9667" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bissamcuttack", cityName: null, lat: "19.8000", lng: "84.2000" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Blangir", cityName: null, lat: "19.8333", lng: "83.4333" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Boksara", cityName: null, lat: "25.8333", lng: "87.2167" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Boldwar", cityName: null, lat: "28.9333", lng: "79.1333" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Boudh", cityName: null, lat: "20.6667", lng: "84.3333" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bougaon", cityName: null, lat: "21.1667", lng: "79.2667" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Brajraj Nagar", cityName: null, lat: "21.8000", lng: "84.5500" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bralinda", cityName: null, lat: "23.0833", lng: "87.4500" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Brganj", cityName: null, lat: "26.8000", lng: "84.9500" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Brihadswar", cityName: null, lat: "21.0333", lng: "84.8500" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Brindarban", cityName: null, lat: "23.5167", lng: "88.9000" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bulandshahr", cityName: null, lat: "28.4170", lng: "77.8563" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Buldhana", cityName: null, lat: "20.5333", lng: "76.1833" },
  { stateCode: "OR", stateName: "Odisha", districtName: "Bundi", cityName: null, lat: "25.4167", lng: "75.6333" },

  // PUNJAB
  { stateCode: "PB", stateName: "Punjab", districtName: null, cityName: null, lat: "31.5497", lng: "74.3436" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Amritsar", cityName: null, lat: "31.6340", lng: "74.8723" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Barnala", cityName: null, lat: "30.9567", lng: "75.5589" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Bathinda", cityName: null, lat: "29.9689", lng: "74.9128" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Faridkot", cityName: null, lat: "30.8167", lng: "74.8333" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Fatehgarh Sahib", cityName: null, lat: "30.6333", lng: "76.3833" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Firozpur", cityName: null, lat: "30.9154", lng: "74.4158" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Gurdaspur", cityName: null, lat: "32.1738", lng: "75.8833" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Jalandhar", cityName: null, lat: "31.7258", lng: "75.5765" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Kapurthala", cityName: null, lat: "31.3945", lng: "75.3945" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Ludhiana", cityName: null, lat: "30.9010", lng: "75.8573" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Malerkotla", cityName: null, lat: "30.5833", lng: "76.2333" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Mansa", cityName: null, lat: "29.5833", lng: "75.4167" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Moga", cityName: null, lat: "30.8230", lng: "75.1863" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Mohali", cityName: null, lat: "30.6396", lng: "76.8194" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Muktsar", cityName: null, lat: "30.1859", lng: "74.5297" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Nawanshahr", cityName: null, lat: "31.6833", lng: "76.1333" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Pathankot", cityName: null, lat: "32.2586", lng: "75.6342" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Patiala", cityName: null, lat: "30.3398", lng: "76.3869" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Rupnagar", cityName: null, lat: "30.9833", lng: "76.5167" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Sangrur", cityName: null, lat: "30.2667", lng: "75.8333" },
  { stateCode: "PB", stateName: "Punjab", districtName: "Tarn Taran", cityName: null, lat: "31.4667", lng: "74.8667" },

  // RAJASTHAN
  { stateCode: "RJ", stateName: "Rajasthan", districtName: null, cityName: null, lat: "27.0238", lng: "74.2179" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Ajmer", cityName: null, lat: "26.4499", lng: "74.6399" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Alwar", cityName: null, lat: "27.5676", lng: "76.6244" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Banswara", cityName: null, lat: "23.5505", lng: "74.4277" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Baran", cityName: null, lat: "25.0878", lng: "76.5561" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Barmer", cityName: null, lat: "25.9242", lng: "71.3968" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Beawar", cityName: null, lat: "26.0939", lng: "74.3119" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Bhilwara", cityName: null, lat: "25.3475", lng: "74.6228" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Bikaner", cityName: null, lat: "28.0229", lng: "71.8315" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Bundi", cityName: null, lat: "25.4167", lng: "75.6333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Chittorgarh", cityName: null, lat: "24.8945", lng: "74.6289" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Churu", cityName: null, lat: "27.8542", lng: "74.6529" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Dausa", cityName: null, lat: "26.8589", lng: "76.3833" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Dholpur", cityName: null, lat: "26.3040", lng: "77.8866" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Dungarpur", cityName: null, lat: "23.8389", lng: "73.7161" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Ganganagar", cityName: null, lat: "29.1965", lng: "73.8844" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Gangaznagar", cityName: null, lat: "29.1965", lng: "73.8844" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Gaurela Pendra Marwai", cityName: null, lat: "21.8500", lng: "82.5000" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Gaya", cityName: null, lat: "24.7958", lng: "84.9789" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Gir Somnath", cityName: null, lat: "21.1667", lng: "70.8000" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Gohad", cityName: null, lat: "26.8589", lng: "76.3833" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Guna", cityName: null, lat: "24.6500", lng: "77.3167" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Gurgaon", cityName: null, lat: "28.4595", lng: "77.0266" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Gurdaspur", cityName: null, lat: "32.1738", lng: "75.8833" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Hanumangarh", cityName: null, lat: "29.5417", lng: "73.3092" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Hasan", cityName: null, lat: "13.0033", lng: "75.7339" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Haveli", cityName: null, lat: "22.1667", lng: "74.5167" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Hawa Mahal", cityName: null, lat: "26.9300", lng: "75.8239" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Hissar", cityName: null, lat: "29.1458", lng: "75.7252" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Hiwan", cityName: null, lat: "24.5000", lng: "82.8833" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Ibrahimpatnam", cityName: null, lat: "13.5667", lng: "78.4667" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Indor", cityName: null, lat: "22.7167", lng: "75.8500" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Indore", cityName: null, lat: "22.7196", lng: "75.8577" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Idar", cityName: null, lat: "23.7333", lng: "72.8333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Itanagar", cityName: null, lat: "28.2164", lng: "93.6053" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jagdalpur", cityName: null, lat: "19.0801", lng: "82.0144" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jahanabad", cityName: null, lat: "25.2000", lng: "85.3000" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jaipai", cityName: null, lat: "26.9124", lng: "75.7873" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jaipur", cityName: null, lat: "26.9124", lng: "75.7873" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jaisalmer", cityName: null, lat: "26.9124", lng: "70.9142" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jajpur", cityName: null, lat: "20.8500", lng: "85.8333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jalor", cityName: null, lat: "25.3635", lng: "72.6197" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jalore", cityName: null, lat: "25.3635", lng: "72.6197" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jalpaiguri", cityName: null, lat: "26.5333", lng: "88.7333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jalore", cityName: null, lat: "25.3635", lng: "72.6197" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jalopada", cityName: null, lat: "25.3635", lng: "72.6197" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jamnagar", cityName: null, lat: "22.4667", lng: "70.0667" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jamui", cityName: null, lat: "24.3500", lng: "84.0833" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jangladesh", cityName: null, lat: "28.0229", lng: "71.8315" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Janjgir-Champa", cityName: null, lat: "21.9333", lng: "81.8667" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jarganj", cityName: null, lat: "25.5000", lng: "85.3333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jarjari", cityName: null, lat: "25.0333", lng: "77.6000" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jashpur", cityName: null, lat: "23.5667", lng: "83.9333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jaunpur", cityName: null, lat: "25.7500", lng: "82.7167" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jaypur", cityName: null, lat: "26.9124", lng: "75.7873" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhajjar", cityName: null, lat: "28.6333", lng: "77.2667" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhalrapatan", cityName: null, lat: "25.0833", lng: "76.1833" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhalawar", cityName: null, lat: "24.5883", lng: "75.6272" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhamba", cityName: null, lat: "20.3500", lng: "82.3333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhambur", cityName: null, lat: "20.3500", lng: "82.3333" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhansi", cityName: null, lat: "25.4358", lng: "78.5976" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhargram", cityName: null, lat: "23.4000", lng: "88.1000" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jharkhandi", cityName: null, lat: "23.6102", lng: "85.2799" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jharia", cityName: null, lat: "23.8333", lng: "86.4167" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jharkhri", cityName: null, lat: "23.6102", lng: "85.2799" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jharipuri", cityName: null, lat: "23.6102", lng: "85.2799" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jheelwahan", cityName: null, lat: "23.6102", lng: "85.2799" },
  { stateCode: "RJ", stateName: "Rajasthan", districtName: "Jhilmili", cityName: null, lat: "23.6102", lng: "85.2799" },

  // DELHI
  { stateCode: "DL", stateName: "Delhi", districtName: null, cityName: null, lat: "28.7041", lng: "77.1025" },
  { stateCode: "DL", stateName: "Delhi", districtName: "Central", cityName: null, lat: "28.6431", lng: "77.2197" },
  { stateCode: "DL", stateName: "Delhi", districtName: "East", cityName: null, lat: "28.5921", lng: "77.2660" },
  { stateCode: "DL", stateName: "Delhi", districtName: "New Delhi", cityName: null, lat: "28.6139", lng: "77.2090" },
  { stateCode: "DL", stateName: "Delhi", districtName: "North", cityName: null, lat: "28.7597", lng: "77.2270" },
  { stateCode: "DL", stateName: "Delhi", districtName: "North East", cityName: null, lat: "28.6708", lng: "77.3075" },
  { stateCode: "DL", stateName: "Delhi", districtName: "North West", cityName: null, lat: "28.7454", lng: "77.0855" },
  { stateCode: "DL", stateName: "Delhi", districtName: "South", cityName: null, lat: "28.5244", lng: "77.1855" },
  { stateCode: "DL", stateName: "Delhi", districtName: "South East", cityName: null, lat: "28.5355", lng: "77.2640" },
  { stateCode: "DL", stateName: "Delhi", districtName: "South West", cityName: null, lat: "28.5166", lng: "77.0766" },
  { stateCode: "DL", stateName: "Delhi", districtName: "West", cityName: null, lat: "28.6500", lng: "77.0333" },

  // UTTAR PRADESH (subset for major cities)
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: null, cityName: null, lat: "26.8467", lng: "80.9462" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Agra", cityName: null, lat: "27.1767", lng: "78.0081" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Allahabad", cityName: null, lat: "25.4358", lng: "81.8463" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Lucknow", cityName: null, lat: "26.8467", lng: "80.9462" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Kanpur", cityName: null, lat: "26.4499", lng: "80.3319" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Varanasi", cityName: null, lat: "25.3209", lng: "82.9789" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Meerut", cityName: null, lat: "28.9845", lng: "77.7064" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Bulandshahr", cityName: null, lat: "28.4170", lng: "77.8563" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Ghaziabad", cityName: null, lat: "28.6692", lng: "77.4538" },
  { stateCode: "UP", stateName: "Uttar Pradesh", districtName: "Noida", cityName: null, lat: "28.5921", lng: "77.3660" },

  // TELANGANA
  { stateCode: "TG", stateName: "Telangana", districtName: null, cityName: null, lat: "18.1124", lng: "79.0193" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Hyderabad", cityName: null, lat: "17.3850", lng: "78.4867" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Rangareddy", cityName: null, lat: "17.4167", lng: "78.3833" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Medak", cityName: null, lat: "18.7500", lng: "78.5333" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Nizamabad", cityName: null, lat: "19.2750", lng: "78.1333" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Adilabad", cityName: null, lat: "19.6667", lng: "78.5333" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Karimnagar", cityName: null, lat: "18.4386", lng: "78.8478" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Khammam", cityName: null, lat: "17.3500", lng: "80.1333" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Mahbubnagar", cityName: null, lat: "16.7333", lng: "77.9500" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Narayanpet", cityName: null, lat: "16.3333", lng: "78.0833" },
  { stateCode: "TG", stateName: "Telangana", districtName: "Warangal", cityName: null, lat: "17.9689", lng: "78.6294" },

  // TRIPURA
  { stateCode: "TR", stateName: "Tripura", districtName: null, cityName: null, lat: "23.9408", lng: "91.9882" },
  { stateCode: "TR", stateName: "Tripura", districtName: "Dhalai", cityName: null, lat: "23.8333", lng: "91.5333" },
  { stateCode: "TR", stateName: "Tripura", districtName: "Khowai", cityName: null, lat: "23.9167", lng: "91.4167" },
  { stateCode: "TR", stateName: "Tripura", districtName: "North Tripura", cityName: null, lat: "24.1333", lng: "91.3000" },
  { stateCode: "TR", stateName: "Tripura", districtName: "Sipahijala", cityName: null, lat: "23.1333", lng: "91.3667" },
  { stateCode: "TR", stateName: "Tripura", districtName: "South Tripura", cityName: null, lat: "22.9167", lng: "91.6000" },
  { stateCode: "TR", stateName: "Tripura", districtName: "West Tripura", cityName: null, lat: "23.8500", lng: "91.3333" },

  // WEST BENGAL
  { stateCode: "WB", stateName: "West Bengal", districtName: null, cityName: null, lat: "24.8735", lng: "88.3635" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Alipurduar", cityName: null, lat: "26.5083", lng: "88.5333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Bankura", cityName: null, lat: "23.9500", lng: "87.0667" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Bardhaman", cityName: null, lat: "23.2500", lng: "87.7333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Birbhum", cityName: null, lat: "24.0833", lng: "87.3333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Burdwan", cityName: null, lat: "23.2500", lng: "87.7333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Cooch Behar", cityName: null, lat: "26.3167", lng: "88.8000" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Cuttack", cityName: null, lat: "20.4833", lng: "85.8833" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Darjeeling", cityName: null, lat: "27.0360", lng: "88.2648" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Dakshin Dinajpur", cityName: null, lat: "25.7833", lng: "88.1333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Dinajpur", cityName: null, lat: "25.6333", lng: "87.9333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "East Midnapore", cityName: null, lat: "21.9500", lng: "87.7500" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Gajole", cityName: null, lat: "23.9500", lng: "87.0667" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Gangarampur", cityName: null, lat: "25.5833", lng: "88.3333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Giridih", cityName: null, lat: "24.1833", lng: "85.3333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Gulbarga", cityName: null, lat: "17.3297", lng: "76.8343" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Hasimara", cityName: null, lat: "26.5083", lng: "88.5333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Hooghly", cityName: null, lat: "23.1667", lng: "88.3667" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Howrah", cityName: null, lat: "22.5958", lng: "88.2636" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Hooghly", cityName: null, lat: "23.1667", lng: "88.3667" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Jalpaiguri", cityName: null, lat: "26.5333", lng: "88.7333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Jessore", cityName: null, lat: "23.1667", lng: "89.0000" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Jhargram", cityName: null, lat: "23.4000", lng: "88.1000" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Kolkata", cityName: null, lat: "22.5726", lng: "88.3639" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Kumarganj", cityName: null, lat: "24.7958", lng: "84.9789" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Maldah", cityName: null, lat: "25.6333", lng: "87.9333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Malda", cityName: null, lat: "25.6333", lng: "87.9333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Medinipur", cityName: null, lat: "22.3833", lng: "87.3000" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Midnapore", cityName: null, lat: "22.3833", lng: "87.3000" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Murshidabad", cityName: null, lat: "24.1833", lng: "88.2667" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Mymensingh", cityName: null, lat: "24.7500", lng: "90.4167" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Nadia", cityName: null, lat: "23.6000", lng: "88.4333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Nakoda", cityName: null, lat: "25.6333", lng: "87.9333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Nalanda", cityName: null, lat: "24.9000", lng: "85.7000" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Nawada", cityName: null, lat: "24.8500", lng: "85.4333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Nellore", cityName: null, lat: "14.4426", lng: "79.9865" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Netrokona", cityName: null, lat: "24.5000", lng: "90.7167" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "North 24 Parganas", cityName: null, lat: "22.5500", lng: "88.7500" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "North Dinajpur", cityName: null, lat: "25.9833", lng: "87.9333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Odisha", cityName: null, lat: "20.9517", lng: "85.0985" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Pabna", cityName: null, lat: "23.9833", lng: "89.2333" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Puruliya", cityName: null, lat: "23.4833", lng: "86.3667" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Rajshahi", cityName: null, lat: "24.3667", lng: "88.6000" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "South 24 Parganas", cityName: null, lat: "21.9500", lng: "88.5833" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Sylhet", cityName: null, lat: "24.9000", lng: "91.8833" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Thakurgaon", cityName: null, lat: "26.1333", lng: "88.4667" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Uttar Pradesh", cityName: null, lat: "26.8467", lng: "80.9462" },
  { stateCode: "WB", stateName: "West Bengal", districtName: "Uttarakhand", cityName: null, lat: "30.0668", lng: "79.0193" },
];

async function seedLocations() {
  console.log(`Seeding ${LOCATIONS_DATA.length} location records...`);

  try {
    const result = await db.insert(locations).values(
      LOCATIONS_DATA.map(loc => ({
        stateCode: loc.stateCode,
        stateName: loc.stateName,
        districtName: loc.districtName,
        cityName: loc.cityName,
        latitude: loc.lat,
        longitude: loc.lng,
        slug: [loc.stateCode, loc.districtName, loc.cityName]
          .filter(Boolean)
          .join("_")
          .toLowerCase()
          .replace(/\s+/g, "-"),
        hierarchyPath: [loc.stateName, loc.districtName, loc.cityName]
          .filter(Boolean)
          .join(" > "),
      }))
    ).onConflictDoNothing();

    console.log(`✅ Seeded locations successfully`);
  } catch (err) {
    console.error("❌ Failed to seed locations:", err);
    throw err;
  }
}

seedLocations().then(() => process.exit(0));
