-- Migration: Shorten recruitment slugs to enterprise-grade format {org-slug}-{year}-{sequential-number}
-- This migration updates all recruitment slugs to semantic, human-readable format

-- Step 1: Add temporary column for new slugs
ALTER TABLE recruitments ADD COLUMN IF NOT EXISTS slug_new TEXT;

-- Step 2: Generate new slugs using sequential numbering per org-year
WITH numbered_recruitments AS (
  SELECT
    r.id,
    CONCAT(
      o.slug,
      '-',
      r.year::TEXT,
      '-',
      LPAD(
        ROW_NUMBER() OVER (
          PARTITION BY r.organization_id, r.year
          ORDER BY r.id
        )::TEXT,
        2,
        '0'
      )
    ) as new_slug
  FROM recruitments r
  JOIN organizations o ON r.organization_id = o.id
)
UPDATE recruitments r
SET slug_new = nr.new_slug
FROM numbered_recruitments nr
WHERE r.id = nr.id;

-- Step 3: Verify no duplicates (should return 0)
SELECT COUNT(*) as duplicate_count FROM (
  SELECT slug_new, COUNT(*) as cnt
  FROM recruitments
  WHERE slug_new IS NOT NULL
  GROUP BY slug_new
  HAVING COUNT(*) > 1
) t;

-- Step 4: Create recruitment_slug_redirects table for SEO mapping
CREATE TABLE IF NOT EXISTS recruitment_slug_redirects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  old_slug TEXT NOT NULL UNIQUE,
  new_slug TEXT NOT NULL,
  recruitment_id BIGINT NOT NULL REFERENCES recruitments(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_old_slug ON recruitment_slug_redirects(old_slug);
CREATE INDEX IF NOT EXISTS idx_recruitment_id ON recruitment_slug_redirects(recruitment_id);

-- Step 5: Populate redirect mapping table with old→new mappings
INSERT INTO recruitment_slug_redirects (old_slug, new_slug, recruitment_id)
SELECT r.slug, r.slug_new, r.id
FROM recruitments r
WHERE r.slug_new IS NOT NULL
ON CONFLICT (old_slug) DO NOTHING;

-- Step 6: Swap old and new slugs (irreversible point)
UPDATE recruitments
SET slug = slug_new
WHERE slug_new IS NOT NULL;

-- Step 7: Drop temporary column
ALTER TABLE recruitments DROP COLUMN slug_new;

-- Step 8: Verification - sample of new slugs grouped by org
SELECT
  o.name as organization,
  r.year,
  COUNT(*) as recruitment_count,
  STRING_AGG(r.slug, ', ' ORDER BY r.slug) as sample_slugs
FROM recruitments r
JOIN organizations o ON r.organization_id = o.id
GROUP BY o.id, o.name, r.year
ORDER BY o.name, r.year DESC
LIMIT 20;

-- Step 9: Verify all recruitments match new format {org-slug}-{year}-{2-digit-number}
SELECT
  COUNT(*) as total_with_new_format,
  COUNT(CASE WHEN slug ~ '^[a-z0-9]+-[0-9]{4}-[0-9]{2}$' THEN 1 END) as matching_format
FROM recruitments;
