-- Migration: Shorten recruitment slugs to enterprise-grade format {org-slug}-{year}-{6char-hash}
-- This migration updates all 1,080 recruitment slugs and creates redirect mapping

-- Step 1: Add temporary column for new slugs
ALTER TABLE recruitments ADD COLUMN IF NOT EXISTS slug_new TEXT;

-- Step 2: Generate new slugs using enterprise format
UPDATE recruitments r
SET slug_new = CONCAT(
  o.slug,
  '-',
  r.year::TEXT,
  '-',
  SUBSTRING(MD5(CONCAT(r.slug, '-', r.id::TEXT)), 1, 6)
)
FROM organizations o
WHERE r.organization_id = o.id;

-- Step 3: Verify no duplicates (should return 0)
SELECT COUNT(*) as duplicate_count FROM (
  SELECT slug_new, COUNT(*) as cnt
  FROM recruitments
  WHERE slug_new IS NOT NULL
  GROUP BY slug_new
  HAVING COUNT(*) > 1
) t;

-- Step 4: Create recruitment_slug_redirects table for SEO mapping
CREATE TABLE IF NOT EXISTS recruitment_slug_redirects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  old_slug TEXT NOT NULL UNIQUE,
  new_slug TEXT NOT NULL,
  recruitment_id BIGINT NOT NULL REFERENCES recruitments(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  INDEX idx_old_slug (old_slug),
  INDEX idx_recruitment_id (recruitment_id)
);

-- Step 5: Populate redirect mapping table
INSERT INTO recruitment_slug_redirects (old_slug, new_slug, recruitment_id)
SELECT r.slug, r.slug_new, r.id
FROM recruitments r
WHERE r.slug_new IS NOT NULL
ON CONFLICT (old_slug) DO NOTHING;

-- Step 6: Swap old and new slugs (irreversible point)
UPDATE recruitments
SET slug = slug_new
WHERE slug_new IS NOT NULL;

-- Step 7: Drop temporary column
ALTER TABLE recruitments DROP COLUMN slug_new;

-- Step 8: Verification query - show sample of new slugs
SELECT id, slug, year, organization_id FROM recruitments ORDER BY id LIMIT 10;

-- Step 9: Verify all recruitments have new format
SELECT COUNT(*) as with_new_format
FROM recruitments
WHERE slug ~ '^[a-z0-9]+-[0-9]{4}-[a-z0-9]{6}$';
